on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

name: make

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: randy_r${{ matrix.config.r }}_py${{ matrix.config.python }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {r: '3.6.3', python: '3.6.11'}
          - {r: '3.6.3', python: '3.7.8'}
          - {r: '3.6.3', python: '3.8.4'}
          - {r: '4.0.2', python: '3.6.11'}
          - {r: '4.0.2', python: '3.7.8'}
          - {r: '4.0.2', python: '3.8.4'}

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: R_VERSION=${{ matrix.config.r }},PYTHON_VERSION=${{ matrix.config.python }},GITHUB_PAT=${{ secrets.PAT }}
          repository: dataintuitive/randpy
          tags: r${{ matrix.config.r }}_py${{ matrix.config.python }}
