on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

name: make

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: randpy_r${{ matrix.config.r }}_py${{ matrix.config.python }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {file: 'buster_r3.6.3_py3.6.11', tags: 'dataintuitive/randpy:r3.6.3_py3.6.11,dataintuitive/randpy:3.6_py3.6'}
          - {file: 'buster_r3.6.3_py3.7.8', tags: 'dataintuitive/randpy:r3.6.3_py3.7.8,dataintuitive/randpy:r3.6_py3.7'}
          - {file: 'buster_r3.6.3_py3.8.3', tags: 'dataintuitive/randpy:r3.6.3_py3.8.3,dataintuitive/randpy:r3.6_py3.8'}
          - {file: 'buster_r4.0.2_py3.6.11', tags: 'dataintuitive/randpy:r4.0.2_py3.6.11,dataintuitive/randpy:r4.0_py3.6'}
          - {file: 'buster_r4.0.2_py3.7.8', tags: 'dataintuitive/randpy:r4.0.2_py3.7.8,dataintuitive/randpy:r4.0_py3.7'}
          - {file: 'buster_r4.0.2_py3.8.3', tags: 'dataintuitive/randpy:r4.0.2_py3.8.3,dataintuitive/randpy:r4.0_py3.8,dataintuitive/randpy:latest'}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build_args: GITHUB_PAT=${{ secrets.PAT }}
          tags: ${{ matrix.config.tags }}
          file: ${{ matrix.config.os }}_r${{ matrix.config.r }}_py${{ matrix.config.python }}.Dockerfile
