on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

name: make

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: randpy_r${{ matrix.config.r }}_py${{ matrix.config.python }}

    env:
      R_LATEST: 4.0
      PY_LATEST: 3.8
      REPO: dataintuitive/randpy

    strategy:
      fail-fast: false
      matrix:
        config:
          - {file: 'r3.6_py2.7', extra_tags: ''}
          - {file: 'r3.6_py3.6', extra_tags: ''}
          - {file: 'r3.6_py3.7', extra_tags: ''}
          - {file: 'r3.6_py3.8', extra_tags: ''}
          - {file: 'r4.0_py2.7', extra_tags: ''}
          - {file: 'r4.0_py3.6', extra_tags: ''}
          - {file: 'r4.0_py3.7', extra_tags: ''}
          - {file: 'r4.0_py3.8', extra_tags: ',dataintuitive/randpy:latest'}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build_args: GITHUB_PAT=${{ secrets.PAT }}
          tags: dataintuitive/randpy:${{ matrix.config.file }}${{ matrix.config.tags }}
          file: ${{ matrix.config.os }}_r${{ matrix.config.r }}_py${{ matrix.config.python }}.Dockerfile
