on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

name: randpy with R 4.0

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: 'randpy_${{ matrix.config.file }}'

    strategy:
      fail-fast: false
      matrix:
        config:
          - {file: 'r4.0', extra_tags: ''}
          - {file: 'r4.0_py2.7', extra_tags: ''}
          - {file: 'r4.0_py3.6', extra_tags: ''}
          - {file: 'r4.0_py3.7', extra_tags: ''}
          - {file: 'r4.0_py3.8', extra_tags: ''}
          - {file: 'r4.0_py3.9', extra_tags: ',dataintuitive/randpy:latest'}
          - {file: 'r4.0_bioc3.11', extra_tags: ''}
          - {file: 'r4.0_py2.7_bioc3.11', extra_tags: ''}
          - {file: 'r4.0_py3.6_bioc3.11', extra_tags: ''}
          - {file: 'r4.0_py3.7_bioc3.11', extra_tags: ''}
          - {file: 'r4.0_py3.8_bioc3.11', extra_tags: ''}
          - {file: 'r4.0_py3.9_bioc3.11', extra_tags: ''}
          - {file: 'r4.0_bioc3.12', extra_tags: ''}
          - {file: 'r4.0_bioc3.12_workaround', extra_tags: ''}
          - {file: 'r4.0_py2.7_bioc3.12', extra_tags: ''}
          - {file: 'r4.0_py3.6_bioc3.12', extra_tags: ''}
          - {file: 'r4.0_py3.7_bioc3.12', extra_tags: ''}
          - {file: 'r4.0_py3.8_bioc3.12', extra_tags: ''}
          - {file: 'r4.0_py3.9_bioc3.12', extra_tags: ''}
          - {file: 'r4.0_py2.7_bioc3.12_workaround', extra_tags: ''}
          - {file: 'r4.0_py3.6_bioc3.12_workaround', extra_tags: ''}
          - {file: 'r4.0_py3.7_bioc3.12_workaround', extra_tags: ''}
          - {file: 'r4.0_py3.8_bioc3.12_workaround', extra_tags: ''}
          - {file: 'r4.0_py3.9_bioc3.12_workaround', extra_tags: ''}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: GITHUB_PAT=${{ secrets.PAT }}
          tags: dataintuitive/randpy:${{ matrix.config.file }}${{ matrix.config.extra_tags }}
          file: dockerfiles/${{ matrix.config.file }}.Dockerfile
          push: true
