on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

name: make

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: randpy_r${{ matrix.config.r }}_py${{ matrix.config.python }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: 'buster', r: '3.6.3', python: '3.6.11', latest: ''}
          - {os: 'buster', r: '3.6.3', python: '3.7.8', latest: ''}
          - {os: 'buster', r: '3.6.3', python: '3.8.3', latest: ''}
          - {os: 'buster', r: '4.0.2', python: '3.6.11', latest: ''}
          - {os: 'buster', r: '4.0.2', python: '3.7.8', latest: ''}
          - {os: 'buster', r: '4.0.2', python: '3.8.3', latest: ', latest'}

    steps:
      - uses: actions/checkout@v2

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: GITHUB_PAT=${{ secrets.PAT }}
          repository: dataintuitive/randpy
          tags: ${{ matrix.config.os }}_r${{ matrix.config.r }}_py${{ matrix.config.python }}${{ matrix.config.latest }}
          dockerfile: ${{ matrix.config.os }}_r${{ matrix.config.r }}_py${{ matrix.config.python }}.Dockerfile
