on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 1"

name: make

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: randpy_r${{ matrix.config.r }}_py${{ matrix.config.python }}

    env:
      R_LATEST: 4.0
      PY_LATEST: 3.8
      REPO: dataintuitive/randpy

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: 'buster', r: '3.6', python: '2.7'}
          - {os: 'buster', r: '3.6', python: '3.6'}
          - {os: 'buster', r: '3.6', python: '3.7'}
          - {os: 'buster', r: '3.6', python: '3.8'}
          - {os: 'buster', r: '4.0', python: '2.7'}
          - {os: 'buster', r: '4.0', python: '3.6'}
          - {os: 'buster', r: '4.0', python: '3.7'}
          - {os: 'buster', r: '4.0', python: '3.8'}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          TAG="r${{ matrix.config.r }}_py${{ matrix.config.python }}"
          DOCKERFILE="dockerfiles/$TAG.Dockerfile"
          docker build --build-arg GITHUB_PAT=${{ secrets.PAT }} -t "$REPO:$TAG" -f "$DOCKERFILE" .
          if [ "${{ matrix.config.r }}" == $R_LATEST ] && [ "${{ matrix.config.py }}" == $PY_LATEST ]] ; then
            docker tag "$REPO:$TAG" "$REPO:latest"
          fi

      - name: Push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $REPO
