on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

name: randpy with R 3.6

jobs:
  build_containers:
    runs-on: 'ubuntu-latest'
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    name: 'randpy_${{ matrix.config.file }}'

    strategy:
      fail-fast: false
      matrix:
        config:
          - {file: 'r3.6', extra_tags: ''}
          - {file: 'r3.6_py2.7', extra_tags: ''}
          - {file: 'r3.6_py3.6', extra_tags: ''}
          - {file: 'r3.6_py3.7', extra_tags: ''}
          - {file: 'r3.6_py3.8', extra_tags: ''}
          - {file: 'r3.6_py3.9', extra_tags: ''}
          - {file: 'r3.6_py3.10', extra_tags: ''}
          - {file: 'r3.6_bioc3.9', extra_tags: ''}
          - {file: 'r3.6_py2.7_bioc3.9', extra_tags: ''}
          - {file: 'r3.6_py3.6_bioc3.9', extra_tags: ''}
          - {file: 'r3.6_py3.7_bioc3.9', extra_tags: ''}
          - {file: 'r3.6_py3.8_bioc3.9', extra_tags: ''}
          - {file: 'r3.6_py3.9_bioc3.9', extra_tags: ''}
          - {file: 'r3.6_py3.10_bioc3.9', extra_tags: ''}
          - {file: 'r3.6_bioc3.10', extra_tags: ''}
          - {file: 'r3.6_py2.7_bioc3.10', extra_tags: ''}
          - {file: 'r3.6_py3.6_bioc3.10', extra_tags: ''}
          - {file: 'r3.6_py3.7_bioc3.10', extra_tags: ''}
          - {file: 'r3.6_py3.8_bioc3.10', extra_tags: ''}
          - {file: 'r3.6_py3.9_bioc3.10', extra_tags: ''}
          - {file: 'r3.6_py3.10_bioc3.10', extra_tags: ''}

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GTHB_PAT }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: GITHUB_PAT=${{ secrets.PAT }}
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/data-intuitive/randpy:${{ matrix.config.file }}${{ matrix.config.extra_tags }}
          file: dockerfiles/${{ matrix.config.file }}.Dockerfile
          push: true
